---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-dashboards
data:
  provisioning-dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: "dashboards"
        orgId: 1
        type: file
        disableDeletion: false
        updateIntervalSeconds: 60
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
data:
  provisioning-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        access: proxy
        orgId: 1
        url: http://mimir-nginx:9009/prometheus
        version: 1
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          alertmanagerUid: "alertmanager"
        secureJsonData:
          httpHeaderValue1: "demo"
        isDefault: true
      - name: Mimir Alertmanager
        uid: alertmanager
        type: alertmanager
        access: proxy
        orgId: 1
        url: http://mimir-nginx:9009/
        version: 1
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          implementation: "cortex"
        secureJsonData:
          httpHeaderValue1: "demo"


