apiVersion: v1
kind: Service
metadata:
  name: mimir
  labels:
    app: mimir
spec:
  type: {{ .Values.mimir.service.type }}
  ports:
    - name: http
      port: {{ .Values.mimir.service.port }}
      targetPort: 8080
  selector:
    app: mimir
