apiVersion: v1
kind: Service
metadata:
  name: mimir-headless
  labels:
    app: mimir
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.mimir.service.port }}
      targetPort: 8080
    - name: memberlist
      port: 7946
      targetPort: 7946
  selector:
    app: mimir
