---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream backend {
           server mimir-headless.default.svc.cluster.local:8080;
        }
    
        server {
            listen 9009;
            access_log /dev/null;
            location / {
                proxy_pass http://backend;
            }
        }
    }