apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-nginx
  namespace: "default"
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: 
        app: nginx
    spec:     
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 9009
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            tcpSocket:
              port: http
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
            tcpSocket:
              port: http
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              readOnly: true
              subPath: nginx.conf
      volumes:
        - configMap:
            name: nginx-config
          name: nginx-config