apiVersion: v1
kind: Service
metadata:
  name: mimir-nginx
  labels:
    app: nginx
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 9009
      targetPort: http
  selector: 
    app: nginx